export interface Province {
  id: string;
  name: string;
}

export const PROVINCES: Province[] = [
  { id: "ha-noi", name: "Hà Nội" },
  { id: "ho-chi-minh", name: "Hồ Chí Minh" },
  { id: "da-nang", name: "Đà Nẵng" },
  { id: "hai-phong", name: "Hải Phòng" },
  { id: "can-tho", name: "Cần Thơ" },
  { id: "binh-duong", name: "Bình Dương" },
  { id: "dong-nai", name: "Đồng Nai" },
  { id: "bac-ninh", name: "Bắc Ninh" },
  { id: "thai-nguyen", name: "Thái Nguyên" },
  { id: "ba-ria-vung-tau", name: "Bà Rịa - Vũng Tàu" },
  { id: "quang-ninh", name: "Quảng Ninh" },
  { id: "hai-duong", name: "Hải Dương" },
  { id: "khanh-hoa", name: "Khánh Hòa" },
  { id: "lam-dong", name: "Lâm Đồng" },
  { id: "thua-thien-hue", name: "Thừa Thiên Huế" },
  { id: "quang-nam", name: "Quảng Nam" },
  { id: "quang-ngai", name: "Quảng Ngãi" },
  { id: "binh-dinh", name: "Bình Định" },
  { id: "thanh-hoa", name: "Thanh Hóa" },
  { id: "nghe-an", name: "Nghệ An" },
  { id: "ha-tinh", name: "Hà Tĩnh" },
  { id: "quang-binh", name: "Quảng Bình" },
  { id: "quang-tri", name: "Quảng Trị" },
  { id: "nam-dinh", name: "Nam Định" },
  { id: "thai-binh", name: "Thái Bình" },
  { id: "ninh-binh", name: "Ninh Bình" },
  { id: "ha-nam", name: "Hà Nam" },
  { id: "vinh-phuc", name: "Vĩnh Phúc" },
  { id: "phu-tho", name: "Phú Thọ" },
  { id: "bac-giang", name: "Bắc Giang" },
  { id: "hoa-binh", name: "Hòa Bình" },
  { id: "son-la", name: "Sơn La" },
  { id: "dien-bien", name: "Điện Biên" },
  { id: "lai-chau", name: "Lai Châu" },
  { id: "lao-cai", name: "Lào Cai" },
  { id: "yen-bai", name: "Yên Bái" },
  { id: "tuyen-quang", name: "Tuyên Quang" },
  { id: "ha-giang", name: "Hà Giang" },
  { id: "cao-bang", name: "Cao Bằng" },
  { id: "bac-kan", name: "Bắc Kạn" },
  { id: "lang-son", name: "Lạng Sơn" },
  { id: "long-an", name: "Long An" },
  { id: "tien-giang", name: "Tiền Giang" },
  { id: "ben-tre", name: "Bến Tre" },
  { id: "tra-vinh", name: "Trà Vinh" },
  { id: "vinh-long", name: "Vĩnh Long" },
  { id: "dong-thap", name: "Đồng Tháp" },
  { id: "an-giang", name: "An Giang" },
  { id: "kien-giang", name: "Kiên Giang" },
  { id: "hau-giang", name: "Hậu Giang" },
  { id: "soc-trang", name: "Sóc Trăng" },
  { id: "bac-lieu", name: "Bạc Liêu" },
  { id: "ca-mau", name: "Cà Mau" },
  { id: "tay-ninh", name: "Tây Ninh" },
  { id: "binh-phuoc", name: "Bình Phước" },
  { id: "dak-lak", name: "Đắk Lắk" },
  { id: "dak-nong", name: "Đắk Nông" },
  { id: "gia-lai", name: "Gia Lai" },
  { id: "kon-tum", name: "Kon Tum" },
  { id: "ninh-thuan", name: "Ninh Thuận" },
  { id: "binh-thuan", name: "Bình Thuận" },
];
